###---------eksempla-------------

### Test root endpoint


GET http://localhost:7007/api/v1/

### GET all candidates
GET http://localhost:7007/api/v1/candidates

### Create new candidates
POST http://localhost:7007/api/v1/candidates
Content-Type: application/json

{
  "name": "Arya Stark",
  "phone": "11223344",
  "educationBackground": "Apprenticeship"
}


###Update candidate by ID
PUT http://localhost:7007/api/v1/candidates/57
Content-Type: application/json

{
  "name": "Arya new strak",
  "phone": "11223344",
  "educationBackground": "Apprenticeship"
}

### DElete candidates by ID
DELETE http://localhost:7007/api/v1/candidates/57


### (Valgfrit) GET candidates filtreret på skill category (US-4)
# Gyldige værdier: PROG_LANG, DB, DEVOPS, FRONTEND, TESTING, DATA, FRAMEWORK
GET http://localhost:7007/api/v1/candidates?category=PROG_LANG

### PUT link a skill to at candidate
PUT http://localhost:7007/api/v1/candidates/56/skills/55

